### ISSUE TITLE
Failed to install plugin "Filename Heading Sync".

### ISSUE THREAD

**Issue by izumin5210** [dvcrn/obsidian-filename-heading-sync#13]
![image](https://user-images.githubusercontent.com/2010175/118487324-8ec04300-b755-11eb-9096-cbfae906f4a6.png)

developer console below:
![image](https://user-images.githubusercontent.com/2010175/118487375-9d0e5f00-b755-11eb-9038-750ae393dced.png)

This is probably because [1.2.0](https://github.com/dvcrn/obsidian-filename-heading-sync/releases/tag/1.3.0) and [1.3.0](https://github.com/dvcrn/obsidian-filename-heading-sync/releases/tag/1.3.0) do not have the transpiled JS and manifest.json uploaded.

@dvcrn  Can you upload them?

**Comment by dvcrn** [comment]
Oh shoot, you're right

**Comment by dvcrn** [comment]
Added the files 👍

**Comment by izumin5210** [comment]
Thank you!
However, the installation now works, but the version is still 1.1.0 🤔 

![image](https://user-images.githubusercontent.com/2010175/118576264-25771900-b7c3-11eb-803c-feef6d62ab5b.png)
![image](https://user-images.githubusercontent.com/2010175/118576215-0e382b80-b7c3-11eb-92e5-4ab67d2fa6d7.png)
![image](https://user-images.githubusercontent.com/2010175/118576237-1728fd00-b7c3-11eb-9ecb-6c6ee996a658.png)

**Comment by izumin5210** [comment]
The uploaded `main.js` does not contain the string `"Ignored Files By Regex"`.
Could it be that you uploaded the wrong file?


```
curl -sfL https://github.com/dvcrn/obsidian-filename-heading-sync/releases/download/1.3.0/main.js | grep -i regex
```

**Comment by dvcrn** [comment]
I've re-uploaded both manifest and transpiled file. Could you give it another go? 

I think this was due to the build system I used not putting the files into the correct spot

**Comment by izumin5210** [comment]
Successfully installed 1.3.0!
Thanks for the quick response!

![image](https://user-images.githubusercontent.com/2010175/118576975-881ce480-b7c4-11eb-964c-d9ae6b801ba6.png)

**Comment by dvcrn** [comment]
Great to hear! Sorry for the messup 😅
