### ISSUE TITLE
When I rename a folder in the folder pane, this plugin renames my current note once for each note in the folder I renamed

### ISSUE THREAD

**Issue by thomasvs** [dvcrn/obsidian-filename-heading-sync#14]
It took me a while to figure this out.  I kept losing a file I was working on.  Turns out the file was still there, but got renamed behind the scenes.

I narrowed it down to the scenario from the summary.

I verified my hunch by doing Ctrl-Z (Undo) in the note that got its header and name rewritten; every Ctrl-Z changes it back to a previous title, which matches the titles from the folder I just renamed.

I'm assuming the plugin listens for file renames globally, but doesn't check whether the file being renamed is the current file I'm in.

**Comment by dvcrn** [comment]
Which version did you use that caused this? 

> I'm assuming the plugin listens for file renames globally, but doesn't check whether the file being renamed is the current file I'm in.

We're checking on the rename event if a file instance exists and do nothing if it doesn't: https://github.com/dvcrn/obsidian-filename-header-sync/blob/bb9b78e8ea58404cccf1b56bb2a8265d32df082b/main.ts#L126-L128

**Comment by dvcrn** [comment]
@thomasvs would you able to try todays v1.4.0 release to see if you can reproduce the issue?
