### ISSUE TITLE
Losing my Today note content

### ISSUE THREAD

**Issue by mrkuramoto** [dvcrn/obsidian-filename-heading-sync#15]
This plugin is overwriting all the content of my today's daily notes with information from another note. Very strange.
I had to use Dropbox history to download the last file with the correct information and than sync among my devices.

The plugin is very nice and very convenient but with this bug, I had to remove it because it is a matter of losing information.

**Comment by dvcrn** [comment]
It overwrote content of the entire note? Can you provide a bit more detail?
