### ISSUE TITLE
Changing the heading of a file with the same name as its parent folder does not work

### ISSUE THREAD

**Issue by hugolundin** [dvcrn/obsidian-filename-heading-sync#17]
Say that you have a folder named `Folder` with a note, `Folder.md`, containing:

```markdown
# Folder
``` 
If I modify the heading to be `# Folder1`, the name `Folder.md` remains. 
Looking in the web inspector, it seems like something gets confused: 

```
Uncaught (in promise) Error: ENOENT: no such file or directory, rename 
'<hidden>/notes/Folder/Folder.md' -> 
'<hidden>/notes/Folder1/Folder.md'
```

While this might be a corner-case, my workflow heavily relies on it. I use index notes in folders and want them to have the same name as the folder to easily be found. My current solution is to name them `Folder (Index).md` but I would like to get away from that. Thank you for a great plugin!

**Comment by dvcrn** [comment]
You're right, this is an oversight by naively using `replace` - https://github.com/dvcrn/obsidian-filename-heading-sync/blob/master/main.ts#L117

**Comment by LeonardoGentile** [comment]
I also uses https://github.com/xpgo/obsidian-folder-note-plugin and this would block me

**Comment by dvcrn** [comment]
I've updated the replace logic to use the full path (`foo.md`) instead of basename (`foo`). This should ensure that only the last part before the extension will get replaced

**Comment by hugolundin** [comment]
Fixed in the now released version. Thank you! 🎉
