### ISSUE TITLE
Can no longer install from Obsidian Community Plugins?

### ISSUE THREAD

**Issue by carmensandoval** [dvcrn/obsidian-filename-heading-sync#20]
Hi - I can't seem to find the plugin in the Community Plugin list anymore. Did the name change or was it taken down?

Thanks!

**Comment by dvcrn** [comment]
Obsidian team disabled it after there was an issue reported with data loss - https://github.com/dvcrn/obsidian-filename-heading-sync/issues/18

A few issues got fixed and the plugin re-submitted to the plugin directory here - https://github.com/obsidianmd/obsidian-releases/pull/373

**Comment by dvcrn** [comment]
It's back now
