### ISSUE TITLE
`# File name` inserted after `## Heading`

### ISSUE THREAD

**Issue by joelmeyerhamme** [dvcrn/obsidian-filename-heading-sync#21]
Sometimes I end with files where the first heading is a subheading (copying subheadings to a new note):

`Blogs.md`
```md
## Blogs
[...]
```

The Plugin then adds the file name as a heading **after** the subheading:

`Blogs.md`
```md
## Blogs
# Blogs
[...]
```

I suggest this be changed to insert the heading at the top of the file. Bonus points for detecting they're the same heading and changing the subheading to a heading, though I wound't consider it a bug if it kept both, as long as they're in the correct order.

P.S. Thanks for resubmitting the plugin, I really appreciate your work!

**Comment by dvcrn** [comment]
I've pushed 1.4.1 this morning actually. Can you update to this version and see if you still have the issue?

**Comment by joelmeyerhamme** [comment]
yep, just updated (and restarted) before posting.

**Comment by dvcrn** [comment]
Fixed in https://github.com/dvcrn/obsidian-filename-heading-sync/releases/tag/1.4.2
