### ISSUE TITLE
File Open Handler as a configurable option?

### ISSUE THREAD

**Issue by bietiekay** [dvcrn/obsidian-filename-heading-sync#24]
Hi probably was the only one using that feature - but actually some parts of my workflow / templating revolves around the file-open handler being called when I open a file and then filename - heading-sync doing it's thing.

I've gone back to 1.4.2 as in the current version this feature is gone. Is there a chance for having it an option that could be enabled/disabled if problems occur - I personally have not run into issues, despite using it quite heavily as mentioned.

Thanks.

**Comment by dvcrn** [comment]
I have also not run into any issues myself, but it was reported at https://github.com/dvcrn/obsidian-filename-heading-sync/issues/18

Maybe we can add it back behind a setting toggle

**Comment by dvcrn** [comment]
This will get added back once https://github.com/dvcrn/obsidian-filename-heading-sync/pull/25 is merged

**Comment by dvcrn** [comment]
Added back in https://github.com/dvcrn/obsidian-filename-heading-sync/releases/tag/1.5.0

**Comment by bietiekay** [comment]
thanks a lot!
