### ISSUE TITLE
Doesn't work when creating a file with Cmd-O

### ISSUE THREAD

**Issue by asherdiamant** [dvcrn/obsidian-filename-heading-sync#26]
This plugin works great when opening a file with Cmd-N, but when creating a file using Cmd-O (when there isn't an existing file with the name you type in, of course). 

Also doesn't work when creating a file through following a link to a non-existing file.

**Comment by sveinnthorarins** [comment]
Ah, this is technically intended behavior. Recently the plugin had some issues with syncing files upon opening them and as a consequence the author removed that functionality. So, now you technically need to actually rename files or modify headings to cause the syncing.

But I agree that it would be best to find a way to bring back this functionality and I believe the author agrees with that as well.

**Comment by sveinnthorarins** [comment]
@dvcrn Actually, I just realized we could totally cover this use case by tapping into the vault's `create` event. I can add that to my existing pull request if you want.

We might also not need to re-introduce the `file-open` event at all then. Adding some commands for manual syncing could serve the other purpose of the `file-open` functionality (the desire to sync upon opening an existing file, full with content, that has never been synced before). That way the plugin never performs anything destructive, right?

**Comment by asherdiamant** [comment]
Oh, I'm sorry, the title is not phrased correctly, though I did correct it in the text. I meant when using Cmd-O to create a note - not open an existing one. I agree that when you open an existing note, you can't tell automatically which way the user will want to sync, so better do that manually. But I would expect all the different options to create a note - Cmd-N, Cmd-O (when there is no note of that name) and clicking through a link (that links to a non-existing note) - would behave the same and sync the title to the filename the user just entered.

I hope that explains my intention better :)

From what you're saying, sounds like the vault create event should cover all of them.

**Comment by sveinnthorarins** [comment]
Yea, I totally got what you meant! Sorry, I sort of went on to ramble further about other issues (in the 2nd paragraph of the 2nd comment). But yes, I'm quite sure the vault's `create` event will fully cover your intentions. And I just meant as of right now, it's not implemented in the code, so your issue isn't a bug but more like a feature request 😄

Thanks for taking the time to post your issue though! Right now, I have a lot of free time so I'm constantly thinking about this plugin although I'm not the author.

**Comment by dvcrn** [comment]
File-open has been re-added in https://github.com/dvcrn/obsidian-filename-heading-sync/releases/tag/1.5.0

This covers
- Opening a file
- Creating a new file (fires the open event)
- Clicking on a link to create a new file

Are there other usecases left that still don't work?

**Comment by asherdiamant** [comment]
No, looks like everything works now. Thanks!
