### ISSUE TITLE
Doesn't work on Today's daily note

### ISSUE THREAD

**Issue by icher** [dvcrn/obsidian-filename-heading-sync#27]
Steps to reproduce:

1. Open today's daily note (sidebar button) and it created file with name something like "2021-09-21";
2. No filename syncing until you change filename (add letter for example);
3. After messing with file name syncing is just fine.

Expected behavior:

1. Open today's daily note;
2. Plugin will add `# 2021-09-21` (just like file name `2021-09-21`) to the top of the note.

Nothing happens after file is created:
![Screenshot_2021-09-22_00-03-11_45](https://user-images.githubusercontent.com/8604717/134215480-11405512-653b-49be-bee6-6ac5300f2ef4.png)

Adding symbol to file name and syncing is ok:
![Screenshot_2021-09-22_00-03-25_73](https://user-images.githubusercontent.com/8604717/134215477-8372ed5d-f4c8-42b3-81fa-dd7fba2c3470.png)

After that syncing is just fine:
![Screenshot_2021-09-22_00-03-38_57](https://user-images.githubusercontent.com/8604717/134215468-dfb1b7b2-2430-4307-89a4-6c1323bb80bc.png)

**Comment by dvcrn** [comment]
Version 1.5.0 re-added the file-open event handler. Can you give it a try? https://github.com/dvcrn/obsidian-filename-heading-sync/releases/tag/1.5.0

**Comment by malachishy** [comment]
I've been experiencing the same issue and can confirm 1.5.0 seems to have fixed it

**Comment by dvcrn** [comment]
Great! I'll close this for now

**Comment by icher** [comment]
Works just fine, thnx.
