### ISSUE TITLE
Date Corruption when opening Image files

### ISSUE THREAD

**Issue by tonyknight** [dvcrn/obsidian-filename-heading-sync#28]
This morning, I noticed that some of my image files in my Obsidian vault were corrupted and didn’t know why. I retraced some steps and found that the very useful Filename Header Sync plugin was corrupting every image that I opened through Obsidian. Here are the details:

1.  I first turned off all plugins and opened some JPG, PNG and PDFs with Obsidian. All good.
2. I turned on Filename Header Sync and tried to open the same images. Each image opened fine, but was modified. As soon as I tried to reopen each image, it failed to open in Obsidian or at the filesystem level. Each image was modified and corrupted. Yikes!!

Here is a demo:
https://www.youtube.com/watch?v=4d7ldsfF9Ew

Tony

**Comment by dvcrn** [comment]
Thanks for the report! I'm reverting the latest changes immediately

**Comment by dvcrn** [comment]
I've pushed 1.5.1 which adds a guard for md files. The issue was caused by the change in https://github.com/dvcrn/obsidian-filename-heading-sync/pull/25 which changed the way this plugin syncs from using the editor for replacing a heading, to using a file handle directly. 

Very sorry this happened!

**Comment by dvcrn** [comment]
I've created a PR to blacklist version 1.5.0 at the obsidian-released repository 

Also cc @sveinnthorarins to have your eyes on this

**Comment by tonyknight** [comment]
Makes sense, and thanks for getting to this so quickly. My data loss was minimal, and I started my career in QA, so this was like a little trip down memory lane for me. :)

**Comment by tonyknight** [comment]
Tested on my end and seems to work fine now. Thanks!
