### ISSUE TITLE
Ignore rules

### ISSUE THREAD

**Issue by ryanjamurphy** [dvcrn/obsidian-filename-heading-sync#3]
First off, thanks for solving a real nuisance with this plugin. 

However, there is one kind of note where I _don't_ want heading-filename sync happening: my calendar notes. So, it'd be fabulous if we could specify some ways of getting the plugin to ignore certain notes.

The simplest option might be to provide some "Ignore folder:" options in the Settings. 

Thanks again!

**Comment by dvcrn** [comment]
Would one folder be enough though? It would be nice to come up with some way to ignore certain things for good

**Comment by ryanjamurphy** [comment]
One would certainly be enough for my use case!

I hear you, though. Adding an arbitrary number of user-customizable settings is tough. The templates plugin is a good example of it.

**Comment by dvcrn** [comment]
Check out https://github.com/dvcrn/obsidian-filename-heading-sync/releases/tag/1.1.0

I added a new "Ignore this file" command that will add the file to a ignored list. You can delete items from that list through the settings:

![](https://user-images.githubusercontent.com/688326/108457012-072d7a00-72b5-11eb-8301-1e4abfb352cb.png)

**Comment by jandamm** [comment]
Would be nice to be able to set this for a whole folder as well.
Setting an ignore for each daily note is be a bit too much.

**Comment by dvcrn** [comment]
Will try to look into it!

**Comment by dvcrn** [comment]
Will try to look into it! 

@jandamm how would a command similar to the current one do that says "ignore this folders"?

**Comment by jandamm** [comment]
Specifying a folder/path in the settings would work for me as well.

**Comment by nielinjie** [comment]
i have a folder for templates (working with templar plugin), all files in this folder should be ignored syncing name, so +1 for ignore folder option request. 
thanks for this plugin, it is great btw.
