### ISSUE TITLE
Templater Can't Use Folder Templater

### ISSUE THREAD

**Issue by WS-HS** [dvcrn/obsidian-filename-heading-sync#31]
Hello , i like this plugin
But , i use Templater too.
Templater now have folder Templater. can use Templater file too new note in OOO Folder.
Like XXX Folder new note can all use Templater_XXX.md to open new file.

But if i use this plugin Templater is can.t work this....
PLS fix this. 

Very THX you make this plugin 👍

**Comment by dvcrn** [comment]
Closed in favor of https://github.com/dvcrn/obsidian-filename-heading-sync/issues/40
