### ISSUE TITLE
When plugin enabled: Templater stops triggering on new file creating (Folder templates)

### ISSUE THREAD

**Issue by mikkovedru** [dvcrn/obsidian-filename-heading-sync#32]
The https://github.com/SilentVoid13/Templater (the top5 Obsidian plugin by popularity) settings:
![image](https://user-images.githubusercontent.com/2521942/139162565-3795317b-0fde-42e5-8c7f-8282ce05beb7.png)
![image](https://user-images.githubusercontent.com/2521942/139162595-b585360f-aa62-4aa1-88bc-0ddf90975f20.png)

These stop working when the Filename Heading Sync plugin is enabled.

## System
- Linux Mint 20.2 Cinnamon
- Obsidian 0.12.19
- the latest versions of both plugins

**Comment by dvcrn** [comment]
Closed in favor of https://github.com/dvcrn/obsidian-filename-heading-sync/issues/40
