### ISSUE TITLE
disable plugin for Excalidraw files

### ISSUE THREAD

**Issue by zsviczian** [dvcrn/obsidian-filename-heading-sync#37]
When a markdown file has the `excalidraw-plugin` frontmatter key, filename-heading-sync should not run, as it results in a corrupted Excalidraw drawing.

https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/305

**Comment by dvcrn** [comment]
Is the extension always .excalidraw for those files?

**Comment by zsviczian** [comment]
In some cases yes, but not always.  My plugin has a compatibility mode with Logseq, in compatibility mode files have a fixed `.excalidraw` extension. Most people however do not use compatibility mode, and their drawings will be standard markdown files with a `.md` extension. The name of the file can be whet ever.

Here's how I check if a file is an Excalidraw file or not:


https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/68391e516348e774c93bb940a381ff141a364bc6/src/main.ts#L1672-L1678


where


https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/68391e516348e774c93bb940a381ff141a364bc6/src/constants.ts#L16

**Comment by dvcrn** [comment]
Do you have an example file I can use for testing?

**Comment by zsviczian** [comment]
Two types of files:
markdown:
[sample file.md](https://github.com/dvcrn/obsidian-filename-heading-sync/files/7763049/sample.file.md)

excalidraw native:
[sample file.zip](https://github.com/dvcrn/obsidian-filename-heading-sync/files/7763070/sample.file.zip)

**Comment by claremacrae** [comment]
I came here to ask for the same thing - to ignore all files called `*.excalidraw.md`

I'm having to go through all the `.excalidraw.md` files in my vault and manually excluded them from this plugin... And remember to do so for future `.excalidraw.md` files I create...

**Comment by dvcrn** [comment]
Excalidraw will get properly excluded in the next release. I just didn't have time to get to it yet

**Comment by dvcrn** [comment]
@claremacrae in the meantime you can add a ignore regex rule like `.*\.excalidraw.md` in the plugin settings, that'll exclude all .excalidraw.md files from this plugin

**Comment by dvcrn** [comment]
Fixed in https://github.com/dvcrn/obsidian-filename-heading-sync/releases/tag/1.5.3
