### ISSUE TITLE
When plugin is enabled, Templater tp.file.move stops working

### ISSUE THREAD

**Issue by paulrudy** [dvcrn/obsidian-filename-heading-sync#38]
This may be related to #32

1. Create a template with text and templater code like the following:
```
Some text
<% tp.file.move("/Folder A/" + tp.file.title ) %>
```
2. Open a note in a different folder (e.g. "Folder B") that is *not* "Folder A" and that is *not* ignored by Filename Heading Sync
3. Create a new note using the template 

Expected result: Newly created note including template text will be created and moved to folder "Folder A"
Actual Result: Newly created note *is* moved to folder "Folder A", but the note is blank—template text is missing.

Note: if Obsidian's active pane is of a note in "Folder A", then we get the expected result.

**Comment by dvcrn** [comment]
Hmm that's odd, does the note with the correct template get created somewhere else as well or is it fully missing?

**Comment by dvcrn** [comment]
Just a memo to self:

Could be the file-open hook that this plugin is using together with `replaceLineInFile` (https://github.com/dvcrn/obsidian-filename-heading-sync/blob/7040b3a45bba0fa3bd69aa78bb33161e6a3804a5/main.ts#L187-L192) that's causing some conflicts with both plugins trying to do something with the file (writing it and moving it)

**Comment by paulrudy** [comment]
> Hmm that's odd, does the note with the correct template get created somewhere else as well or is it fully missing?

No, the correct template doesn't get created anywhere.

> Could be the file-open hook that this plugin is using together with `replaceLineInFile` ([`7040b3a`/main.ts#L187-L192](https://github.com/dvcrn/obsidian-filename-heading-sync/blob/7040b3a45bba0fa3bd69aa78bb33161e6a3804a5/main.ts#L187-L192)) that's causing some conflicts with both plugins trying to do something with the file (writing it and moving it)
> 
> I'm curious to see if this gets rid of the issue because filename-heading-sync should exclude acting on the file

Yes, when templater moves the file to a folder excluded by filename-heading-sync, the problem doesn't arise. It's definitely a conflict between the two plugins.

[This comment](https://discord.com/channels/686053708261228577/875720842443649045/924050029944135760) in the Discord hypothesized what might be going on:

>so it looks like filename heading sync is listening for a rename event and then firing off the code to add the H1 to the note. My guess is:
>- tp.file.move is basically the same as a rename and so fires the rename event.
>- this triggers the header sync which swallows the rest of the template

**Comment by dvcrn** [comment]
A random guess, but I don't use templater so I don't know if it'll work

If we were to ignore all files that have `tp.file` and things like it in it, you reckon that'd work? It would still trigger on the new file that has no tp.file in it though

**Comment by dvcrn** [comment]
Closed in favor of https://github.com/dvcrn/obsidian-filename-heading-sync/issues/40
