### ISSUE TITLE
Insert new heading after YAML frontmatter if present

### ISSUE THREAD

**Issue by dvcrn** [dvcrn/obsidian-filename-heading-sync#4]

**Comment by mkschulze** [comment]
Yes please, because for example this breaks working with Flashcards for Anki, since those have a YAML definition at first of the note.

**Comment by derwish-pro** [comment]
Faced the same problem.

**Comment by dvcrn** [comment]
I agree that we should add this 👍 
I'm just a bit loaded, so pull requests are very welcome!

This is the line where the plugin inserts a new heading. So check here if the lines are frontmatter, if they are, use the next line and so on

**Comment by zgagnon** [comment]
I put a PR up on this. You can actually get the frontmatter locations from the App object, so I set it up to not even start looking until after the frontmatter is skipped (I routinely use frontmatter with 10+ lines for use with the [Obsidian Dataview Plugin](https://github.com/blacksmithgu/obsidian-dataview))

**Comment by artmg** [comment]
Shame that @zgagnon didn't manage to find time to get his PR past QA. I was hoping to use this handy plugin, however frontmatter functionality is key for me, and unfortunately I don't have his coding skills.

**Comment by LeonardoGentile** [comment]
> So check here if the lines are frontmatter, if they are, use the next line and so on

Actually this wouldn't be enough to cover all cases.
This is an example I use often

```
---
alias: [Data cleaning]
---
[[Link to related note1]], [[Link to related note2]]

# Title
```

So I guess the best solution would be to search for the first occurrence of H1 `# some text` within the file without the assumptions on which line it should be

**Comment by dvcrn** [comment]
Yeah that's an easy change if that's enough to fix this

**Comment by harmtemolder** [comment]
> So I guess the best solution would be to search for the first occurrence of H1 `# some text` within the file without the assumptions on which line it should be

Isn’t that what already happens in [`findHeading`](https://github.com/dvcrn/obsidian-filename-heading-sync/blob/bb9b78e8ea58404cccf1b56bb2a8265d32df082b/main.ts#L167)? Except that it’s limited by `this.settings.numLinesToCheck`, with a maximum of 10, which is not enough for long frontmatter.

**Comment by zgagnon** [comment]
New versions of the Obsidian API allow direct access to the frontmatter. We can use this to identify and skip all frontmatter. Once we do that, we can insert the title wherever we want. This would also help not remove any first level heading that exists on the file prior to applying the plugin.

Challenge is pulling in the new API version - the types don't line up.

**Comment by LeonardoGentile** [comment]
> > So I guess the best solution would be to search for the first occurrence of H1 `# some text` within the file without the assumptions on which line it should be
> 
> Isn’t that what already happens in [`findHeading`](https://github.com/dvcrn/obsidian-filename-heading-sync/blob/bb9b78e8ea58404cccf1b56bb2a8265d32df082b/main.ts#L167)? Except that it’s limited by `this.settings.numLinesToCheck`, with a maximum of 10, which is not enough for long frontmatter.

I don't think that's my case tough. I don't have any  frontmatter longer than 4 or 5 lines (usually just the alias), so my H1 is within 10 lines but it seems to be replaced anyway with another H1 at the first line

**Comment by dvcrn** [comment]
@zgagnon which API are you referring to?

**Comment by dvcrn** [comment]
Would someone here be able to give the PR https://github.com/dvcrn/obsidian-filename-heading-sync/pull/19 a go? I don't use front matter but in my few test files it skips it now

**Comment by jpchauny** [comment]
Facing the same problem. The plugin was automatically disabled by Obsidian.

**Comment by zgagnon** [comment]
> @zgagnon which API are you referring to?

Obsidian API `CachedMetadata` includes a reference to frontmatter cache, which includes `pos` of frontmatter and all frontmatter contents:

https://github.com/obsidianmd/obsidian-api/blob/b0aa06eab03d8c39c0733949da5aa1edc2084b01/obsidian.d.ts#L382

**Comment by dvcrn** [comment]
I ended up adding a bit of custom logic to detect fronmatter (just go from the top until it sees a ---), but we can always swap that out later if needed. 

Got pushed with todays v1.4.0 release. Please give it a go and let me know if adjustments are needed

**Comment by artmg** [comment]
I have not yet performed extensive testing to edge cases, but this is looking good so far!
Many thanks for your kind work
