### ISSUE TITLE
Bug: When enabled, Templater Folder Templates stop working

### ISSUE THREAD

**Issue by chrisgrieser** [dvcrn/obsidian-filename-heading-sync#40]
I think this is due to the plugin inserting text into the file before Templater's "on the creation of an empty file" condition is checked.

<img width="1079" alt="Screenshot 2022-01-23 13 38 42" src="https://user-images.githubusercontent.com/73286100/150678781-005951f7-3b60-4b32-bbc4-61ed7a9d529a.png">

**Comment by dvcrn** [comment]
Are you able to get around this when you ignore the Templater/ folder in this plugins settings?

**Comment by chrisgrieser** [comment]
You mean the folder where I store my templater templates? That folder I do already ignore

**Comment by brandonkboswell** [comment]
I am also running into this.

**Comment by gmaciocci** [comment]
Same issue here

**Comment by JohnPaton** [comment]
Same!

**Comment by dvcrn** [comment]
Since I don't use templater it would be helpful if anyone had ideas what to try to resolve this instead of just commenting same 😇

**Comment by brandonkboswell** [comment]
The issue appears to be that this plugin adds content prior to templater's hook to add the default template for a given folder. Perhaps adding an option to have Obsidian Filename Heading Sync only add titles to pages with content would make them compatible with each other?

**Comment by dvcrn** [comment]
How about adding a option to disable the "file open" event hook? So it only modified on save 

Another idea, though hacky, would be to add artificial delay after a file has been opened 

I'm guessing there is no way to identify a templater file since it's empty first? If we can then we could just add a ignore rule

**Comment by chrisgrieser** [comment]
> How about adding a option to disable the "file open" event hook? So it only modified on save

that would work, if you restricted it to the *opened* file – applying the sync to the file you are leaving to open another is part of what I (and many) people like about the plugin.

> Another idea, though hacky, would be to add artificial delay after a file has been opened

maybe a bit less hacky would be to check file creation date before running the sync, and only run the sync if the fiel creation is x seconds ago – I assume it is during that time span that templater runs it's templates?

**Comment by dvcrn** [comment]
Let's try to make the file-open hook optional and see if that solves some of these issues. I also like the functionality that a new file automatically has the headline synced on creation, so I don't want to mess with that too much

From my understanding templater is creating the file first, then inserting the templated content? So both plugins overwrite each other. The best would be if there was some way to detect that a file has been created by templater...

**Comment by JohnPaton** [comment]
As far as I know Templater doesn't create the file, it just listens for the file creation event and fills the new file with content

![image](https://user-images.githubusercontent.com/18459252/153844862-f4e0bdba-4635-47d0-a6c3-6be22a2477e9.png)

**Comment by dvcrn** [comment]
Ah I see, so it hooks into file creation... Wonder if we can extract that setting somehow (or detect that it's enabled) and then change the behavior of filenamen-heading-sync

**Comment by chrisgrieser** [comment]
Automatically changing behavior if this plugin depending on the templater setting would be great, but I think a simple toggle in the settings of this plugin would ahead be a good start.

**Comment by dvcrn** [comment]
Hey folks! [1.6.0](https://github.com/dvcrn/obsidian-filename-heading-sync/releases/tag/1.6.0) is out with an option to disable the file-open hook

<img width="748" alt="Screen Shot 2022-03-11 at 11 32 58" src="https://user-images.githubusercontent.com/688326/157791015-fde220fb-9b38-4873-a5b8-ace6433c19c3.png">

Please give it a go and check if this fixes issues with templater

**Comment by chrisgrieser** [comment]
seems it fixes the issue for me! :)

**Comment by dvcrn** [comment]
Great to hear! Let's wait for some of the others to report back, then we can close this for now.

Would be good if we can find some automatic solution to detect templater

**Comment by rdimaio** [comment]
Disabling the "Use File Open Hook" fixes the issue for me as well. Thanks a lot :)

**Comment by dvcrn** [comment]
Great, I'll close this for now

**Comment by dobrealeksa** [comment]
Disabling the "Use File Open Hook" does not fix the issue, at least not anymore... 🥲

**Comment by dvcrn** [comment]
I've created an issue over at the templater repository - https://github.com/SilentVoid13/Templater/issues/924
