### ISSUE TITLE
Suggestion: Add Ctrl+P command for manual sync

### ISSUE THREAD

**Issue by everruler12** [dvcrn/obsidian-filename-heading-sync#43]
This plugin looks like it could be really convenient, but I don't want every file to be renamed with the header. Example: filename of "LYT" with header "Linking Your Thinking" (specifying what the acronym is).

If there was an option to trigger the sync only for the note that's active in the editor, there wouldn't be worry about destructive editing with opening files I've already created that I want to keep named differently from the heading.

**Comment by dvcrn** [comment]
I'm going to add a config option to disable the file-open hook, related to https://github.com/dvcrn/obsidian-filename-heading-sync/issues/40

Just didn't get to doing it yet 😄
