### ISSUE TITLE
Manual sync hotkeys missing from command palette

### ISSUE THREAD

**Issue by mikkovedru** [dvcrn/obsidian-filename-heading-sync#57]
Relates to @mnaoumov's feature #56.

When I go to Settings/Hotkeys I see both new options:
![image](https://user-images.githubusercontent.com/2521942/182720778-559cca47-8cc1-4677-9b98-2801df873821.png)

But in Command Palette (Ctrl+P) those options are missing:
![image](https://user-images.githubusercontent.com/2521942/182720897-3980e99f-b3fb-4ce3-ad9c-a5c75c4e991f.png)

**Comment by mnaoumov** [comment]
@mikkovedru 

Works as expected

![image](https://user-images.githubusercontent.com/735878/182721537-16d21129-6581-421f-89a6-b2a591516d23.png)

Please ensure you have an active editor

**Comment by mikkovedru** [comment]
You were correct. The issue was Obsidian having an active focus on the file manager.

Thank you!
