### ISSUE TITLE
Only syncing selected files (manually)

### ISSUE THREAD

**Issue by santiyounger** [dvcrn/obsidian-filename-heading-sync#6]
Hey this is an amazing plugin, thank you for making this!

The only thing I'm stuggling with is how destructive in can be to older notes where I've used #h1 headings in the past. Since the plugin acts accross the whole vault.

I saw there's a command to ignore sync for file.

What I think would make this plugin amazing is the ability to have settings to configure things

A setting that would be great would be to have this plugin off for all files.

And once we are on an specific note, we can decide to turn on title & heading sync only for that file.

That way we have control over the files we choose to sync.

I'd love to know the scope of this, hopefully it's not too hard to implement, but I'd love to know your thoughts on this

**Comment by megclaypool** [comment]
Chiming in:
I *love* this plugin for most of my notes, but I'd like to be able to exclude all my periodic (daily/weekly/monthly) notes, including newly generated ones. (For example, my daily notes' filenames have to be in the form YYYYMMDD to show up properly in the calendar, but that makes an ugly, ugly heading.) 
Alas, this plugin is overwriting the pretty heading in my template with the filename. While that's exactly what it's designed to do, it's the one instance in my vault where I don't want it to happen 😛  It would be nice if we could include/exclude entire directories, so I could continue to use your plugin all my with my regular notes and just exclude the notes in my "Dated Items" folder.

**Comment by dvcrn** [comment]
@megclaypool Would an ignore pattern work for this?

**Comment by dvcrn** [comment]
I've added ignore rules through regex patterns in https://github.com/dvcrn/obsidian-filename-heading-sync/pull/12. 

Please give it a try and see if that works for you. I'll close this issue for now, if it's not resolved let me know and I'll re-open it. 

For now I'm against having it work the other way of only syncing specific files (through tags for example), but we can revisit it later if there's enough demand

**Comment by megclaypool** [comment]
Hey, sorry to bug you but I'm having trouble with the update...

The update to 1.3.0 appeared in my community plugins in Obsidian, so I tried updating that way. It claimed to be updating, but the version number never changed and the update never applied. 

I also tried downloading the zip from the current release and dropping it directly into my .obsidian plugins folder. Then I restarted Obsidian and tried turning on the plugin. However, I just get the message: "Failed to load plugin obsidian-filename-heading-sync".

"Hmmmm..." I said, and opened the dev tools on the off chance was an informative console message. Lo and behold, Plugin failure: obsidian-filename-heading-sync Error: ENOENT: no such file or directory, open '/path_to_my_vault/.obsidian/plugins/obsidian-filename-heading-sync/main.js' "What are you talking about?! It's right... Oh..." The main.js file was instead named `main.ts` "Ah hah!" I exclaimed, feeling very clever. I renamed the file, restarted Obsidian, and clicked the toggle to enable the plugin...

And now the console says: 
> Plugin failure: obsidian-filename-heading-sync SyntaxError: Cannot use import statement outside a module
    at eval (<anonymous>)
    at app.js:1
    at t.<anonymous> (app.js:1)
    at app.js:1
    at Object.next (app.js:1)
    at s (app.js:1)
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.enablePlugin @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.enablePluginAndSave @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
(anonymous) @ app.js:1
t.setValue @ app.js:1
t.onClick @ app.js:1

And that's where my amateur sleuthing ground to a halt 🙁  So you're going to want to rename your "main.ts" file, but I've got no advice on the next bit :/ Let me know if there's any thing I can do to help -- I'm really looking forward to this update 😀

**Comment by santiyounger** [comment]
thanks @dvcrn  I'll let you know if I run into issues. Doing the 

> For now I'm against having it work the other way of only syncing specific files (through tags for example), but we can revisit it later if there's enough demand

I get you, hopefully there's more usecases for this in the future, but I totally understand.

Thanks for your hard work

**Comment by megclaypool** [comment]
Just FYI, I was able to resolve my issue by deleting everything in the "obsidian-filename-heading-sync" folder (created by downloading the zip in the release) and instead just downloading the main.js and manifest.json files and putting them in there. 

Not only does the plugin load, but it looks like the ignore rule is exactly what I needed -- none of the files in my "Dated" folder are getting touched, but everything else is getting a fabulous header 😀  ❤️

**Comment by dvcrn** [comment]
Great to hear you sorted it out! I wonder what happened there, it should have downloaded it automatically
