### ISSUE TITLE
Plugin, theme, and config used in showcased gif

### ISSUE THREAD

**Issue by dityaaa** [dvcrn/obsidian-filename-heading-sync#66]
I really like your obsidian style used in the showcased gif. What should I do to replicate your obsidian?

![image](https://user-images.githubusercontent.com/25661768/206009274-fab8e1be-67bf-413f-bd8c-89ce5351a097.png)

**Comment by dvcrn** [comment]
That's the minimal theme (https://github.com/kepano/obsidian-minimal) together with Sliding panes (https://github.com/deathau/sliding-panes-obsidian)
