### ISSUE TITLE
Feature request: support alternative `Title\n ====` heading syntax

### ISSUE THREAD

**Issue by wilbowma** [dvcrn/obsidian-filename-heading-sync#72]
I have a lot of existing documenting that use the alternative Heading 1 syntax:
```
Title
===
```

And I prefer it. It would be nice if the plugin could:
1. Support adding headings in this syntax.
2. Support recognizing existing headings in this syntax.

**Comment by dvcrn** [comment]
Happy to add it, but I don't personally use this so I can't promise when I'll get around to it. 

Pull requests are as always very welcome :)
