### ISSUE TITLE
Strip custom characters when setting filename from title

### ISSUE THREAD

**Issue by danielwe** [dvcrn/obsidian-filename-heading-sync#8]
I'd like to be able to customize the stripping of special characters when going from title to filename. In my particular case, I'd prefer if the characters `#^[]@` were stripped, and possibly also `()`, in addition to the special characters that are already removed by the plugin. This exact selection of characters is personal preference---the point is that the ability to customize this transformation would be awesome.

(This is sort of similar to #7, but relates to the opposite transformation, i.e., title -> filename rather than filename -> title, and only represents a minor extension of existing functionality.)

**Comment by dvcrn** [comment]
@ArchieAtkinson added support for adding custom characters in the settings in https://github.com/dvcrn/obsidian-filename-heading-sync/pull/9

The exclusion will be both ways, let me know if that works for your usecase
