### ISSUE TITLE
Version 1.9.1 Always wants to be updated

### ISSUE THREAD

**Issue by dokmanc** [dvcrn/obsidian-filename-heading-sync#83]
I upgraded to version 1.9.1 and after a successful update, Obsidian still thinks that there is a newer version available.

**Comment by oschrenk** [comment]
The release manifest still lists `1.9.0` while the tag or the release says 1.9.1. 

It seems that Obsidian checks tags to see if a new release is available and then uses the manifest to tell the current version.

It also seems that something went wrong during the release of 1.9.1 itself https://github.com/dvcrn/obsidian-filename-heading-sync/actions/runs/8094455312/job/22119182202

Not sure if that is related

**Comment by evanharmon1** [comment]
I am experiencing the same issue. Uninstalling did not fix so I think @oschrenk is correct.

**Comment by dvcrn** [comment]
Oh damn, sorry about that, for some reason I didn't receive email notifications and this went by me. Fixed th emanifest

**Comment by gdigesu** [comment]
It is 100% now. Thank you!
