### ISSUE TITLE
One line of code in the article will cause the "Sync Filename to Heading" to fail.

### ISSUE THREAD

**Issue by victorwoo** [dvcrn/obsidian-filename-heading-sync#93]
I noticed that after adding this line of code to my article, the "Sync Filename to Heading" operation stopped working. Whether I use `CTRL+P` > `Sync Filename to Heading` or simply save the file, no Heading is added to my article.

However, as soon as I remove this line of code, everything works fine again.

![sync-filename-to-heading-error](https://github.com/user-attachments/assets/6e56e47f-bfe6-4a89-80af-54a0702cc721)

I've attached the problematic article and screenshots for your reference. 
[sync-filename-to-heading-error.zip](https://github.com/user-attachments/files/17655677/sync-filename-to-heading-error.zip)

All settings are set to default:

![plugin-settings](https://github.com/user-attachments/assets/6c594b89-e260-458c-a23a-842138ee4cc7)

Thank you!

**Comment by victorwoo** [comment]
Yes, the `#` character at the start of a line is typically utilized in PowerShell and bash scripts. Consequently, the code within the fenced block ought to be omitted from the logic. Wishing you progress 👍

**Comment by dvcrn** [comment]
Started pushing a fix for this in https://github.com/dvcrn/obsidian-filename-heading-sync/pull/95?new_mergebox=true

I didn't have time to properly test this yet so I won't release it yet but hopefully the next days

**Comment by dvcrn** [comment]
Should be fixed now in https://github.com/dvcrn/obsidian-filename-heading-sync/releases/tag/1.9.2

**Comment by dvcrn** [comment]
Just to fully wrap this up, could you try the newest version and confirm whether this is fixed?

**Comment by victorwoo** [comment]
> Just to fully wrap this up, could you try the newest version and confirm whether this is fixed?

Yes, I have carried out the test and it is functioning as expected. I truly appreciate your prompt response and the efforts you've put into resolving this.
