### ISSUE TITLE
Run Plugin over All Notes?

### ISSUE THREAD

**Issue by AlJohri** [dvcrn/obsidian-filename-heading-sync#96]
Is there a way to run this plugin over all notes in a vault in bulk? That would be very useful for cross compatibility with NotePlan: https://help.noteplan.co/article/61-use-noteplan-with-obsidian

**Comment by dvcrn** [comment]
Sorry, while I can see this being useful, it's a bit out of scope of this plugin 

I think you can just write a script that opens all your documents one by one, then close it, which should trigger this plugin. 
You don't even need a plugin to do this, just open dev tools and paste it in

Something like

```js
const allFiles = this.app.vault.getFiles();
allFiles.forEach((file) => {
    console.log(file);
    // open the file, then close it after a few seconds 
}
```

**Comment by AlJohri** [comment]
Thanks for the pointer! Here's the final script in case anyone needs it:

```javascript
const allFiles = this.app.vault.getFiles();

async function openAndCloseFiles() {
    for (const file of allFiles) {
        if (file.extension === "md") {
            // Open the file in a new leaf
            const leaf = this.app.workspace.getLeaf(true);
            await leaf.openFile(file);

            // Wait for 500ms before closing the file
            await new Promise(resolve => setTimeout(resolve, 500));

            // Close the file by detaching the leaf
            leaf.detach();
        }
    }
}

openAndCloseFiles();
```

I had to add a 500ms delay otherwise either the heading wouldn't apply or the tabs will fill up faster than they would close. Given the delay, I wouldn't recommend this exact approach to anyone with even a moderately sized vault. I have about ~2000 notes in my vault which would take 2000 / 2 / 60 = ~17 minutes. It's currently been running for 10 minutes as I type this. Hopefully finishes soon!

**Comment by dvcrn** [comment]
Great to hear that you figured it out so quick and thanks for sharing the script 💪
